spring.application.name=userservice
spring.datasource.url=jdbc:postgresql://localhost:5432/user_service
spring.datasource.username=default
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create-drop
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=trace
jwt.secret=your-very-long-secret-key-should-be-at-least-32-characters
jwt.expiration=3600000