spring.application.name=transaction-service
spring.datasource.url=jdbc:postgresql://localhost:5432/transaction_service
spring.datasource.username=default
spring.datasource.password=password
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always